### ISSUE TITLE
Nan

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/isd-prioritization#4]
Its possible to break the calculations if you 0 out the subcomponents of a category. Probably creates a divide by 0 scenario.

<img width="756" alt="screen shot 2015-12-13 at 11 00 00 am" src="https://cloud.githubusercontent.com/assets/1913857/11768667/dcef2f0c-a188-11e5-979c-7e070d9c2c02.png">

**Comment by danbjoseph** [comment]
because of the way it's being calculated... with the sum of the weighted categories divided by the weightings for each category (in order to keep the scale to 0-10)... a category with all it's sub-categories set to zero should also be zero. so now in addition to catching the NaNs the category slider will be set to zero if you set all the subs to zero. however this results in the potentially confusing behavior of being unable to change the category from zero if the subs are all set to zero.
860c884907bc694f7f67ecf074e41b81c695f908
